import { AppItem, BrewOutdated, BrewPackage, PermissionSnapshot, ScanSummary } from './types';

export const MOCK_APPS: AppItem[] = [
  {
    id: 'mock-spotify',
    name: 'Spotify',
    appPath: '/Applications/Spotify.app',
    bundleId: 'com.spotify.client',
    sizeBytes: 374_865_920,
    source: 'mock',
  },
  {
    id: 'mock-figma',
    name: 'Figma',
    appPath: '/Applications/Figma.app',
    bundleId: 'com.figma.Desktop',
    sizeBytes: 418_220_032,
    source: 'mock',
  },
  {
    id: 'mock-vscode',
    name: 'Visual Studio Code',
    appPath: '/Applications/Visual Studio Code.app',
    bundleId: 'com.microsoft.VSCode',
    sizeBytes: 512_443_392,
    source: 'mock',
  },
];

export const MOCK_UNINSTALL_SUMMARY: ScanSummary = {
  mode: 'uninstall',
  title: 'Spotify',
  subtitle: 'Deep uninstall preview with the app bundle and the residues tied to it.',
  app: MOCK_APPS[0],
  scannedRoots: [
    '/Applications',
    '~/Library/Application Support',
    '~/Library/Preferences',
    '~/Library/Caches',
  ],
  inaccessibleRoots: [],
  items: [
    {
      id: 'mock-app',
      label: 'Spotify.app',
      path: '/Applications/Spotify.app',
      category: 'application',
      confidence: 'high',
      reason: 'Installed app bundle selected for complete uninstall.',
      appName: 'Spotify',
      sizeBytes: 374_865_920,
      modifiedAt: '2026-07-01T10:00:00.000Z',
      isDirectory: true,
      selected: true,
    },
    {
      id: 'mock-support',
      label: 'Application Support',
      path: '~/Library/Application Support/Spotify',
      category: 'application-support',
      confidence: 'high',
      reason: 'Folder name matches the selected app.',
      appName: 'Spotify',
      sizeBytes: 124_000_000,
      modifiedAt: '2026-07-01T10:02:00.000Z',
      isDirectory: true,
      selected: true,
    },
    {
      id: 'mock-cache',
      label: 'Caches',
      path: '~/Library/Caches/com.spotify.client',
      category: 'caches',
      confidence: 'high',
      reason: 'Cache path includes the bundle identifier.',
      appName: 'Spotify',
      sizeBytes: 48_500_000,
      modifiedAt: '2026-07-01T10:04:00.000Z',
      isDirectory: true,
      selected: true,
    },
    {
      id: 'mock-hidden',
      label: '.spotifynp-helper',
      path: '~/Library/Application Support/.spotifynp-helper',
      category: 'hidden',
      confidence: 'medium',
      reason: 'Hidden entry shares the app name prefix.',
      appName: 'Spotify',
      sizeBytes: 1_280_000,
      modifiedAt: '2026-07-01T10:06:00.000Z',
      isDirectory: true,
      selected: false,
    },
  ],
};

export const MOCK_ORPHAN_SUMMARY: ScanSummary = {
  mode: 'residues',
  title: 'Residual Files',
  subtitle: 'Deep scan for leftovers from apps that are no longer installed.',
  app: null,
  scannedRoots: ['~/Library/Application Support', '~/Library/Preferences', '~/Library/Caches'],
  inaccessibleRoots: [],
  items: [
    {
      id: 'orphan-spotify-pref',
      label: 'Spotify Preferences',
      path: '~/Library/Preferences/com.spotify.client.plist',
      category: 'preferences',
      confidence: 'high',
      reason: 'Preference file still references an app that is not installed.',
      appName: 'Spotify',
      sizeBytes: 12_200,
      modifiedAt: '2026-07-01T09:30:00.000Z',
      isDirectory: false,
      selected: true,
    },
    {
      id: 'orphan-sketch-cache',
      label: 'Sketch Cache',
      path: '~/Library/Caches/com.bohemiancoding.sketch3',
      category: 'caches',
      confidence: 'medium',
      reason: 'Cache path suggests Sketch but the app was not found.',
      appName: 'Sketch',
      sizeBytes: 6_420_000,
      modifiedAt: '2026-07-01T08:12:00.000Z',
      isDirectory: true,
      selected: false,
    },
    {
      id: 'orphan-unknown-log',
      label: 'Unknown orphan log',
      path: '~/Library/Logs/.legacy-sync-helper.log',
      category: 'hidden',
      confidence: 'low',
      reason: 'Hidden log looks app-specific but no parent app was identified.',
      appName: null,
      sizeBytes: 88_100,
      modifiedAt: '2026-07-01T07:18:00.000Z',
      isDirectory: false,
      selected: false,
    },
  ],
};

export const MOCK_SYSTEM_SUMMARY: ScanSummary = {
  mode: 'system',
  title: 'System Junk',
  subtitle: 'Generic caches and logs that are not tied to one uninstall flow.',
  app: null,
  scannedRoots: ['~/Library/Caches', '~/Library/Logs', '~/Library/Saved Application State'],
  inaccessibleRoots: [],
  items: [
    {
      id: 'system-cache-1',
      label: 'Global cache folder',
      path: '~/Library/Caches/com.apple.Safari.SafeBrowsing',
      category: 'caches',
      confidence: 'medium',
      reason: 'Large cache folder inside a generic system-junk category.',
      appName: null,
      sizeBytes: 28_400_000,
      modifiedAt: '2026-07-01T09:45:00.000Z',
      isDirectory: true,
      selected: false,
    },
    {
      id: 'system-log-1',
      label: 'Crash log archive',
      path: '~/Library/Logs/DiagnosticReports',
      category: 'logs',
      confidence: 'medium',
      reason: 'Generic log category selected by the user.',
      appName: null,
      sizeBytes: 4_120_000,
      modifiedAt: '2026-07-01T09:05:00.000Z',
      isDirectory: true,
      selected: false,
    },
  ],
};

export const MOCK_PERMISSION_SNAPSHOT: PermissionSnapshot = {
  checkedAt: '2026-07-01T12:00:00.000Z',
  permissions: [
    {
      target: 'privacy-full-disk-access',
      status: 'not-granted',
      detail: 'Protected Library folders may stay hidden until Full Disk Access is granted in System Settings.',
    },
    {
      target: 'privacy-accessibility',
      status: 'granted',
      detail: 'Accessibility is available, so the app can guide focus back to cleanup-related system prompts.',
    },
  ],
};

export const MOCK_BREW_PACKAGES: BrewPackage[] = [
  {name: 'node', outdated: true},
  {name: 'python@3.12', outdated: false},
  {name: 'git', outdated: false},
  {name: 'ripgrep', outdated: true},
  {name: 'neovim', outdated: false},
  {name: 'tmux', outdated: false},
  {name: 'jq', outdated: false},
  {name: 'fzf', outdated: true},
  {name: 'htop', outdated: false},
  {name: 'wget', outdated: false},
];

export const MOCK_BREW_OUTDATED: BrewOutdated[] = [
  {name: 'node', currentVersion: '22.4.0', latestVersion: '22.5.0', pinned: false},
  {name: 'ripgrep', currentVersion: '14.1.0', latestVersion: '14.1.1', pinned: false},
  {name: 'fzf', currentVersion: '0.55.0', latestVersion: '0.56.0', pinned: false},
];
