import { AppItem, PermissionSnapshot, ScanSummary, StartupSnapshot } from './types';

export const MOCK_APPS: AppItem[] = [
  {
    id: 'mock-spotify',
    name: 'Spotify',
    appPath: '/Applications/Spotify.app',
    bundleId: 'com.spotify.client',
    sizeBytes: 374_865_920,
    source: 'mock',
  },
  {
    id: 'mock-figma',
    name: 'Figma',
    appPath: '/Applications/Figma.app',
    bundleId: 'com.figma.Desktop',
    sizeBytes: 418_220_032,
    source: 'mock',
  },
  {
    id: 'mock-vscode',
    name: 'Visual Studio Code',
    appPath: '/Applications/Visual Studio Code.app',
    bundleId: 'com.microsoft.VSCode',
    sizeBytes: 512_443_392,
    source: 'mock',
  },
];

export const MOCK_UNINSTALL_SUMMARY: ScanSummary = {
  mode: 'uninstall',
  title: 'Spotify',
  subtitle: 'Deep uninstall preview with the app bundle and the residues tied to it.',
  app: MOCK_APPS[0],
  scannedRoots: [
    '/Applications',
    '~/Library/Application Support',
    '~/Library/Preferences',
    '~/Library/Caches',
  ],
  inaccessibleRoots: [],
  items: [
    {
      id: 'mock-app',
      label: 'Spotify.app',
      path: '/Applications/Spotify.app',
      category: 'application',
      confidence: 'high',
      reason: 'Installed app bundle selected for complete uninstall.',
      appName: 'Spotify',
      sizeBytes: 374_865_920,
      modifiedAt: '2026-07-01T10:00:00.000Z',
      isDirectory: true,
      selected: true,
    },
    {
      id: 'mock-support',
      label: 'Application Support',
      path: '~/Library/Application Support/Spotify',
      category: 'application-support',
      confidence: 'high',
      reason: 'Folder name matches the selected app.',
      appName: 'Spotify',
      sizeBytes: 124_000_000,
      modifiedAt: '2026-07-01T10:02:00.000Z',
      isDirectory: true,
      selected: true,
    },
    {
      id: 'mock-cache',
      label: 'Caches',
      path: '~/Library/Caches/com.spotify.client',
      category: 'caches',
      confidence: 'high',
      reason: 'Cache path includes the bundle identifier.',
      appName: 'Spotify',
      sizeBytes: 48_500_000,
      modifiedAt: '2026-07-01T10:04:00.000Z',
      isDirectory: true,
      selected: true,
    },
    {
      id: 'mock-hidden',
      label: '.spotifynp-helper',
      path: '~/Library/Application Support/.spotifynp-helper',
      category: 'hidden',
      confidence: 'medium',
      reason: 'Hidden entry shares the app name prefix.',
      appName: 'Spotify',
      sizeBytes: 1_280_000,
      modifiedAt: '2026-07-01T10:06:00.000Z',
      isDirectory: true,
      selected: false,
    },
  ],
};

export const MOCK_ORPHAN_SUMMARY: ScanSummary = {
  mode: 'residues',
  title: 'Residual Files',
  subtitle: 'Deep scan for leftovers from apps that are no longer installed.',
  app: null,
  scannedRoots: ['~/Library/Application Support', '~/Library/Preferences', '~/Library/Caches'],
  inaccessibleRoots: [],
  items: [
    {
      id: 'orphan-spotify-pref',
      label: 'Spotify Preferences',
      path: '~/Library/Preferences/com.spotify.client.plist',
      category: 'preferences',
      confidence: 'high',
      reason: 'Preference file still references an app that is not installed.',
      appName: 'Spotify',
      sizeBytes: 12_200,
      modifiedAt: '2026-07-01T09:30:00.000Z',
      isDirectory: false,
      selected: true,
    },
    {
      id: 'orphan-sketch-cache',
      label: 'Sketch Cache',
      path: '~/Library/Caches/com.bohemiancoding.sketch3',
      category: 'caches',
      confidence: 'medium',
      reason: 'Cache path suggests Sketch but the app was not found.',
      appName: 'Sketch',
      sizeBytes: 6_420_000,
      modifiedAt: '2026-07-01T08:12:00.000Z',
      isDirectory: true,
      selected: false,
    },
    {
      id: 'orphan-unknown-log',
      label: 'Unknown orphan log',
      path: '~/Library/Logs/.legacy-sync-helper.log',
      category: 'hidden',
      confidence: 'low',
      reason: 'Hidden log looks app-specific but no parent app was identified.',
      appName: null,
      sizeBytes: 88_100,
      modifiedAt: '2026-07-01T07:18:00.000Z',
      isDirectory: false,
      selected: false,
    },
  ],
};

export const MOCK_SYSTEM_SUMMARY: ScanSummary = {
  mode: 'system',
  title: 'System Junk',
  subtitle: 'Generic caches and logs that are not tied to one uninstall flow.',
  app: null,
  scannedRoots: ['~/Library/Caches', '~/Library/Logs'],
  inaccessibleRoots: [],
  items: [
    {
      id: 'system-cache-1',
      label: 'Global cache folder',
      path: '~/Library/Caches/com.apple.Safari.SafeBrowsing',
      category: 'caches',
      confidence: 'medium',
      reason: 'Large cache folder inside a generic system-junk category.',
      appName: null,
      sizeBytes: 28_400_000,
      modifiedAt: '2026-07-01T09:45:00.000Z',
      isDirectory: true,
      selected: false,
    },
    {
      id: 'system-log-1',
      label: 'Crash log archive',
      path: '~/Library/Logs/DiagnosticReports',
      category: 'logs',
      confidence: 'medium',
      reason: 'Generic log category selected by the user.',
      appName: null,
      sizeBytes: 4_120_000,
      modifiedAt: '2026-07-01T09:05:00.000Z',
      isDirectory: true,
      selected: false,
    },
  ],
};

export const MOCK_PERMISSION_SNAPSHOT: PermissionSnapshot = {
  checkedAt: '2026-07-01T12:00:00.000Z',
  permissions: [
    {
      target: 'privacy-full-disk-access',
      status: 'not-granted',
      detail: 'Protected Library folders may stay hidden until Full Disk Access is granted in System Settings.',
    },
    {
      target: 'privacy-accessibility',
      status: 'granted',
      detail: 'Accessibility is available, so the app can guide focus back to cleanup-related system prompts.',
    },
    {
      target: 'privacy-automation',
      status: 'unknown',
      detail: 'macOS does not expose a stable API for Automation approval state. Verify it manually if follow-up flows stall.',
    },
    {
      target: 'login-items',
      status: 'needs-manual-review',
      detail: 'Background Items should be reviewed manually after each cleanup because macOS may re-enable them independently.',
    },
  ],
};

export const MOCK_STARTUP_SNAPSHOT: StartupSnapshot = {
  checkedAt: '2026-07-01T12:05:00.000Z',
  globalError: null,
  categories: [
    {
      id: 'login-items',
      title: 'Login Items',
      subtitle: 'Apps that request launch when the user session starts.',
      state: 'permission-needed',
      detail: 'Review Login Items in System Settings because macOS does not expose a reliable third-party inventory here.',
      count: 0,
    },
    {
      id: 'launch-agents-user',
      title: 'Launch Agents (User)',
      subtitle: 'Per-user launchd jobs loaded from the user Library.',
      state: 'available',
      detail: 'Two user agents were found in the current preview dataset.',
      count: 2,
    },
    {
      id: 'launch-agents-system',
      title: 'Launch Agents (System)',
      subtitle: 'System-wide agents that still run in a user GUI session.',
      state: 'available',
      detail: 'One system Launch Agent is currently visible.',
      count: 1,
    },
    {
      id: 'launch-daemons',
      title: 'Launch Daemons',
      subtitle: 'System launchd jobs that start outside the user session.',
      state: 'available',
      detail: 'One daemon was found in the preview dataset.',
      count: 1,
    },
    {
      id: 'services',
      title: 'Brew Services',
      subtitle: 'Homebrew-managed background services.',
      state: 'unsupported',
      detail: 'Homebrew services will be mapped in the updates/startup integration milestone.',
      count: 0,
    },
  ],
  items: [
    {
      id: 'launch-agents-user:spotify',
      category: 'launch-agents-user',
      label: 'com.spotify.webhelper',
      displayName: 'Spotify Helper',
      description: 'Launches the Spotify helper after login for notifications and quick resume.',
      plistPath: '/Users/demo/Library/LaunchAgents/com.spotify.webhelper.plist',
      executablePath: '/Applications/Spotify.app/Contents/MacOS/Spotify',
      program: '/Applications/Spotify.app/Contents/MacOS/Spotify',
      programArguments: ['/Applications/Spotify.app/Contents/MacOS/Spotify', '--background'],
      runAtLoad: true,
      keepAlive: false,
      disabledInPlist: false,
      enabled: true,
      loaded: true,
      pid: 412,
      lastExitStatus: 0,
      scope: 'user',
      requiresAdmin: false,
      supportsToggle: true,
      source: 'plist',
      domain: 'gui/501',
      errorMessage: null,
    },
    {
      id: 'launch-agents-user:tailscale',
      category: 'launch-agents-user',
      label: 'com.tailscale.ipn.macsys',
      displayName: 'Tailscale IPN',
      description: 'Keeps the Tailscale networking agent available in the current user session.',
      plistPath: '/Users/demo/Library/LaunchAgents/com.tailscale.ipn.macsys.plist',
      executablePath: '/Applications/Tailscale.app/Contents/MacOS/Tailscale',
      program: null,
      programArguments: ['/Applications/Tailscale.app/Contents/MacOS/Tailscale', 'ipn'],
      runAtLoad: true,
      keepAlive: true,
      disabledInPlist: false,
      enabled: true,
      loaded: true,
      pid: 588,
      lastExitStatus: 0,
      scope: 'user',
      requiresAdmin: false,
      supportsToggle: true,
      source: 'plist',
      domain: 'gui/501',
      errorMessage: null,
    },
    {
      id: 'launch-agents-system:adobe',
      category: 'launch-agents-system',
      label: 'com.adobe.GC.Invoker-1.0',
      displayName: 'Adobe GC Invoker',
      description: 'System Launch Agent that invokes Adobe background checks in GUI sessions.',
      plistPath: '/Library/LaunchAgents/com.adobe.GC.Invoker-1.0.plist',
      executablePath: '/Library/Application Support/Adobe/AdobeGCClient/AdobeGCClient.app/Contents/MacOS/AdobeGCClient',
      program: null,
      programArguments: [
        '/Library/Application Support/Adobe/AdobeGCClient/AdobeGCClient.app/Contents/MacOS/AdobeGCClient',
      ],
      runAtLoad: true,
      keepAlive: false,
      disabledInPlist: false,
      enabled: true,
      loaded: false,
      pid: null,
      lastExitStatus: 0,
      scope: 'system',
      requiresAdmin: true,
      supportsToggle: false,
      source: 'plist',
      domain: 'system',
      errorMessage: null,
    },
    {
      id: 'launch-daemons:brew-mysql',
      category: 'launch-daemons',
      label: 'homebrew.mxcl.mysql',
      displayName: 'MySQL Daemon',
      description: 'LaunchDaemon that keeps the MySQL server available at boot.',
      plistPath: '/Library/LaunchDaemons/homebrew.mxcl.mysql.plist',
      executablePath: '/opt/homebrew/opt/mysql/bin/mysqld_safe',
      program: '/opt/homebrew/opt/mysql/bin/mysqld_safe',
      programArguments: ['/opt/homebrew/opt/mysql/bin/mysqld_safe'],
      runAtLoad: true,
      keepAlive: true,
      disabledInPlist: false,
      enabled: true,
      loaded: true,
      pid: 731,
      lastExitStatus: 0,
      scope: 'system',
      requiresAdmin: true,
      supportsToggle: false,
      source: 'plist',
      domain: 'system',
      errorMessage: null,
    },
  ],
};
